import db from './index';

export const createTables = () => {

  db.execSync(`
    CREATE TABLE IF NOT EXISTS USUARIOS (
      MATRICULA INTEGER,
      NOME TEXT,
      CODUSUR INTEGER,
      CODSUPERV INTEGER,
      CODFILIAL INTEGER,
      USUARIOBD TEXT,
      SENHA TEXT,
      PERCACRESCIMOVENDA REAL,
      TIPOVEND TEXT,
      VLCORRENTE REAL,
      VLLIMCRED REAL,
      PERMAXVENDA TEXT,
      AREAATUACAO TEXT,
      SALDO REAL,
      SALDOATUAL REAL
    );
  `);

  db.execSync(`
    CREATE TABLE IF NOT EXISTS CLIENTES (
      CODCLI INTEGER,
      CLIENTE TEXT,
      FANTASIA TEXT,
      BLOQUEIO TEXT,
      CODCLIPRINC INTEGER,
      ENDERENT TEXT,
      BAIRROENT TEXT,
      MUNICENT TEXT,
      ESTENT TEXT,
      CODUSUR1 INTEGER,
      CODUSUR2 INTEGER,
      CODUSUR3 INTEGER,
      CODPRACA INTEGER,
      PRACA TEXT,
      CODCOB TEXT,
      COBRANCA TEXT,
      CODPLPAG INTEGER,
      PLANOPAG TEXT,
      CODREDE INTEGER,
      NUMREGIAO INTEGER,
      CODATIV INTEGER,
      RAMO TEXT,
      CNPJ TEXT,
      LIMCRED REAL,
      PEDABERTO REAL,
      VLABERTO REAL,
      SUPERV1 INTEGER,
      SUPERV2 INTEGER,
      SUPERV3 INTEGER,
      TELENT TEXT,
      TELCOB TEXT,
      TELCOM TEXT,
      EMAIL TEXT,
      EMAILNFE TEXT,
      PLPAGNEG TEXT,
      OBSENTREGA1 TEXT,
      UTILIZAPEDCLINFE TEXT,
      CODFILIALNF INTEGER,
      IEENT TEXT,
      CALCULAST TEXT,
      CONTRIBUINTE TEXT,
      CONSUMIDORFINAL TEXT
    );
  `);

  db.execSync(`
    CREATE TABLE IF NOT EXISTS PRODUTOS (
      CODPROD INTEGER,
      DESCRICAO TEXT,
      PVENDA REAL
    );
  `);

};